version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=service_platform
      - JWT_SECRET=your_jwt_secret_key
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306" 
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=service_platform
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  frontend_node_modules:
  backend_node_modules: